# Dataset metadata
dataset:
  name: "10_minutes_air_temperature"
  description: "DWD 10-minute air temperature measurements"
  version: "1.0"

# Data provider (no email until verified)
provider:
  name: "Deutscher Wetterdienst (DWD)"
  url: "https://opendata.dwd.de"

# Crawler configuration (remote URLs + output)
crawler:
  # Join rule: base_url + root_path + optional subfolder
  base_url: "https://opendata.dwd.de/climate_environment/CDC/"
  root_path: "observations_germany/climate/10_minutes/air_temperature/"
  subfolders:
    historical: "historical/"
    recent: "recent/"
    now: "now/"
    meta_data: "meta_data/"

  # Where the crawler writes the URL list JSONL (repo-relative)
  output_urls_jsonl: "data/dwd/1_crawl_dwd/10_minutes_air_temperature_urls.jsonl"

  # HTTP behavior
  request:
    timeout_seconds: 20
    max_retries: 3
    request_delay_seconds: 0.5         # CLI --throttle overrides
    user_agent: "ClimaStation/1.0"

# Downloader destination (repo-relative)
downloader:
  root_dir: "data/dwd/2_downloaded_files/"

# (Optional today, useful for the downloader/planner to filter quickly)
source:
  file_patterns:
    historical_zip: "10minutenwerte_TU_*_hist.zip"
    recent_zip: "10minutenwerte_TU_*_akt.zip"
    now_zip: "10minutenwerte_TU_*_now.zip"
    metadata_zip: "Meta_Daten_zehn_min_tu_*.zip"
